# Generated by Django 4.2.1 on 2023-05-18 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_profession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profession',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
