# Generated by Django 4.2.1 on 2023-05-19 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_profession_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profession',
        ),
    ]
