# Generated by Django 4.2.1 on 2023-05-20 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_role_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
