# Generated by Django 4.2.1 on 2023-05-22 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cook',
        ),
    ]
