# Generated by Django 4.2.1 on 2023-05-22 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='status',
            new_name='statuss',
        ),
    ]
