# Generated by Django 4.2.1 on 2023-05-22 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0014_rename_status_order_statuss'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cook',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cook', to=settings.AUTH_USER_MODEL),
        ),
    ]
