# Generated by Django 4.2.1 on 2023-05-26 21:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0015_order_cook'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_start', models.DateTimeField()),
                ('data_end', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='dishhasorder',
            name='count',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='dishhasorder',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishs', to='api.dish'),
        ),
        migrations.AlterField(
            model_name='dishhasorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishs', to='api.order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='statuss',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, related_name='statuss', to='api.status'),
        ),
        migrations.CreateModel(
            name='UserOnShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift', to='api.shift')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
