# Generated by Django 4.2.1 on 2023-05-28 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_shift_alter_dishhasorder_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='statuss',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, related_name='statuss', to='api.status'),
        ),
    ]
